//Error Handling

// let a = 19;
try {
  console.log(a);
} catch (error) {
  //   console.log(error);
  console.log("Something went wrong!!");
}
